### ISSUE TITLE
task 2 missing igc files?

### ISSUE THREAD

**Issue by kuaka** [FlareTiming/2018-forbes-flatlands-score#2]
I cannot identify tracks for:
Vic Hare
Simon West
Ross Smith
Robert Davies
Randal Clotworthy
Peter Adriaans
Neale Halsall
Mikhail Karmazin
Justinas Pleikys
Gennadiy Khramov
Frank Chetcuti
Anatoly Reyter

I see that they have min dist in the html results. however many of them have penalties.. so there must be an igc??
Also I see that there are many pilots with min dist with dist points = 108 however they have a total points of more than this:

eg Halsall got 10km, 108 dist points and 499 total points beating myers who flew 156km! \
what is the logic there?
21 | Neale Halsall | M | AUS | Moyes RX 4 Pro |   |   |   |   | 10.0 | 108.2 |   |   |   | 499

**Comment by philderbeast** [comment]
These pilots did fly but have no tracks. Have a look at the docs on [pilot groups](https://flare-timing.readthedocs.io/en/latest/extract-input.html#pilot-groups).

![Screen Shot 2020-11-19 at 7 54 02 AM](https://user-images.githubusercontent.com/633283/99669080-8ef8b380-2a3c-11eb-8cda-a0bd3cac5620.png)

**Comment by philderbeast** [comment]
Vic Hare is scored for minimum distance but then gets the negative penalty applied.

```xml
<FsParticipant id="74">
  <FsResultPenalty penalty="0" penalty_points="-242" penalty_reason=""/>
  <FsFlightData distance="0.000" bonus_distance="0.000" started_ss="" finished_ss=""
    tracklog_filename="" lc="0" iv="0"/>
  <FsResult rank="31" points="350" distance="10" ss_time="00:00:00"
    distance_points="108.2" linear_distance_points="15.19" difficulty_distance_points="92.98"
    time_points="0" arrival_points="0" leading_points="0"
    penalty_points_auto="0" penalty_reason_auto=""
    real_distance="10" last_distance="-1.79769313486232E+305"/>
</FsParticipant
```

**Comment by kuaka** [comment]
ok thanks for the clarification. the official results don't show positive penalties so it is rather confusing (not a flaretiming issue I know). 
e.g:
![image](https://user-images.githubusercontent.com/19358239/99704655-8caa5e00-2afd-11eb-8b13-48247b7f9447.png)
![image](https://user-images.githubusercontent.com/19358239/99704683-97fd8980-2afd-11eb-9afc-fb40e215eaad.png)
