### ISSUE TITLE
definition of stop_time in fsdb?

### ISSUE THREAD

**Issue by kuaka** [FlareTiming/2018-forbes-flatlands-score#3]
in [forbes 2018 clean xml](https://github.com/FlareTiming/2018-forbes-flatlands-score/blob/master/forbes2018.clean-fsdb.xml)
I can see that every task has a stop_time.
for example task 1:
FsTaskState task_state="STOPPED" score_back_time="15" cancel_reason="" stop_time="2017-12-30T18:23:00+11:00"/
task 2:
FsTaskState task_state="REGULAR" score_back_time="15" cancel_reason="" stop_time="2017-12-31T17:34:00+11:00"/

what is the defintion of stop_time?
is it the time that the task was stopped? (if so there is a bug/error that puts this time on every task even if it was not stopped)
or is it something else? in task 2 the stop_time looks like the 1st time a pilot crossed ESS.

if this is not an error there needs to be an issue raised on airscore that is importing the fsdb and treating it as stopped time.
AFAIK airscore is ignoring task_state and treating it like a comment. Is this the official way to "stop" a task in a fsdb?

**Comment by philderbeast** [comment]
@kuaka I've compared `*.clean-fsdb.xml` with the original `*.fsdb` that I got from the scorer. The tasks are identical. The first task is stopped but the second one is not.

```xml
<FsTask id="1">
  <FsTaskState task_state="STOPPED" score_back_time="15" cancel_reason="" stop_time="2017-12-30T18:23:00+11:00"/>
</FsTask>
```

```xml
<FsTask id="2">
  <FsTaskState task_state="REGULAR" score_back_time="15" cancel_reason="" stop_time="2017-12-31T17:34:00+11:00"/>
</FsTask>
```

I ignore the stop time unless the task state is stopped so I parse the first two tasks as:

```yaml
# *.comp-input.yaml
tasks:
- taskName: Task 1
  stopped:
    announced: 2017-12-30T07:23:00Z
    retroactive: 2017-12-30T07:08:00Z
- taskName: task 2
  stopped: null
```

Did the scorer set the stop time for regular tasks for a reason? I should ask the scorer.

**Comment by kuaka** [comment]
closing this as it appears that stop_time is standard for tasks (even if not stopped) based on other fsdb files. airscore now copes with this.
