### ISSUE TITLE
track file folder - cleaning required

### ISSUE THREAD

**Issue by kuaka** [FlareTiming/2018-forbes-flatlands-score#4]
I appreciate that the Task folders with the igc files are probably verbatim from the competition scorer however in trying to re-score this competition, in the case where we have multiple track files per pilot per task, it is impossible to know if I am using the correct file.

Some igc files also have names that are hard to associate with a pilot. (maybe pilot name is inside the file, I haven't checked)

**Comment by philderbeast** [comment]
There's one folder per task and one file per pilot per task in the `*.fsdb`. That there are other files there is a good test for flare-timing. Multiple tracks on the same day from one or more varios do get downloaded at the scorer's desk.

Are you manually zipping and uploading the whole lot to airScore? Could you use the same filtering, by looking up the file to use in the `*.fsdb` and discarding the others?

**Comment by kuaka** [comment]
I am deleting all the 'tracks' in airscore (just placeholders after
importing a fsdb with the pilot result) I am leaving the ABS, Min DIST, DNF
so I know I don't need a track for them then I am zipping and uploading to
airScore all the igcs in the folder. I am then
 manually searching for the tracks that are not automatically picked up
from the zip things like "rohant.igc" (instead of Rohan_Taylor). Also
airScore will not, in the first instance, process bad quality tracks, I
have to force it. So Tony Armstrong always has an igc without altitude, I
have to manually upload his track again and choose to process it regardless
of it's faults.

I was unaware that the filenames were in the fsdb. It could be an
enhancement of airScore to process these when importing. Again, the
importing of fsdb into airScore was intended purely as a way to get
external results into a ladder. Using it for testing brings out the things
like this that could be enhanced if we want to use fsdb to re-process a
comp in airScore in it's entirety. At the moment, I am not keen to trawl
through the fsdb and one by one upload tracks to airScore. A nice thing
about airScore is that once an igc has been processed it puts it into a
folder with a clean name so that we can take the entire folder and have
only the tracks that were used and all nicely named. This would be a great
feature for flare timing to adopt.

**Comment by kuaka** [comment]
Perhaps a quick fix would be to write an independent script to read fsdb pilot names and file names and copy/rename the igc files with correct name.

**Comment by kuaka** [comment]
I have created a script to clean up the names and make it much easier to get the right files into airScore.

https://github.com/kuaka/fsdb_igc

As the usual workflow will be that a comp is first scored in airScore and then Flare Timing and not vice versa, this issue can be closed.

**Comment by philderbeast** [comment]
> As the usual workflow will be that a comp is first scored in airScore and then Flare Timing and not vice versa, this issue can be closed.

The test comps I've collected were first scored in FS.
